### PR TITLE
Add event links

### PR DESCRIPTION
**Pull request by mchugh19**
Added jqzabbix calls to popup.js to lookup latest eventid for given triggerid. This could possibly be added to ZabbixService.js, but I'm not sure there is much gain from that. 

Having eventid allowed adding eventid and ack links.

### CODE REVIEW

**Comment by rsanting** [comment]
I can merge this but I think it would also be a good idea to make you a collaborator on this. (I'm not quite sure yet how to give you permissions to also upload new versions to mozilla but I'm sure that also could be arranged). Would you be interested in that?

**Comment by mchugh19** [comment]
Sure. I'd be game.

Relatedly, would you have any interest in uploading to chrome as well?
Seems the Gigatec folks might be busy.

**Comment by rsanting** [comment]
You're a collaborator now.  I think the license allows uploading to chrome. I can look into uploading chrome builds this weekend.

**Comment by rsanting** [comment]
Also what would be nice is if you could setup your editor to put new lines at the end of files. It's a bit cleaner that way.

**Pull request merged**
